definitions:
  go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  go-clean-arch_internal_user_adapter_delivery_http_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  go-clean-arch_internal_user_adapter_delivery_http_dto.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  go-clean-arch_internal_user_adapter_delivery_http_dto.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  go-clean-arch_internal_user_adapter_delivery_http_dto.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      description: API for user to login
      operationId: UserLogin
      parameters:
      - description: Input Fields
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/go-clean-arch_internal_user_adapter_delivery_http_dto.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-clean-arch_internal_user_adapter_delivery_http_dto.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
      summary: Login (User)
      tags:
      - Auth
  /api/auth/signup:
    post:
      description: API for user to register a new account
      operationId: UserSignUp
      parameters:
      - description: Input Fields
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/go-clean-arch_internal_user_adapter_delivery_http_dto.SignUpRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/go-clean-arch_internal_user_adapter_delivery_http_dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
      summary: Signup (User)
      tags:
      - Auth
  /api/user/me:
    get:
      description: API for authenticated user to get their own profile
      operationId: UserMe
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-clean-arch_internal_user_adapter_delivery_http_dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/go-clean-arch_internal_shared_adapter_delivery_http_middleware.ErrorResponse'
      security:
      - Bearer: []
      summary: Get User Profile
      tags:
      - User
swagger: "2.0"
