// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-wire/pkg/api"
	"go-wire/pkg/api/handler"
	"go-wire/pkg/config"
	"go-wire/pkg/db"
	"go-wire/pkg/repository"
	"go-wire/pkg/usecase"
)

// Injectors from wire.go:

func InitailizeApi(config2 config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(config2)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	serverHTTP := http.NewServerHTTP(userHandler)
	return serverHTTP, nil
}
