// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	delivery "go-clean-arch/internal/shared/adapter/delivery"
	userHandler "go-clean-arch/internal/user/adapter/delivery/http/handler"
	userRepo "go-clean-arch/internal/user/adapter/repository"
	userUsecase "go-clean-arch/internal/user/usecase"
	"go-clean-arch/pkg/auth"
	"go-clean-arch/pkg/config"
	"go-clean-arch/pkg/db"
)

// Injectors from wire.go:

// InitializeAPI builds and injects all dependencies, returning the HTTP server.
func InitializeAPI(cfg config.Config) (*delivery.Server, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := userRepo.NewUserRepository(gormDB)
	tokenService := auth.NewTokenService(cfg)
	userManager := userUsecase.NewUserManager(userRepository, tokenService)
	userHandlerObj := userHandler.NewUserHandler(userManager)
	server := delivery.NewServer(cfg, userHandlerObj, tokenService)
	return server, nil
}
