// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-clean-arch/internal/shared/adapter/delivery"
	"go-clean-arch/internal/user/adapter/delivery/http/handler"
	"go-clean-arch/internal/user/adapter/delivery/http/router"
	"go-clean-arch/internal/user/adapter/repository"
	"go-clean-arch/internal/user/usecase"
	"go-clean-arch/pkg/auth"
	"go-clean-arch/pkg/config"
	"go-clean-arch/pkg/crypto"
	"go-clean-arch/pkg/db"
)

// Injectors from wire.go:

// InitializeAPI builds and injects all dependencies, returning the HTTP server.
func InitializeAPI(cfg config.Config) (*delivery.Server, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	tokenService := auth.NewTokenService(cfg)
	bcryptHasher := crypto.NewBcryptHasher()
	tokenTTLs := provideTokenTTLs(cfg)
	userManager := usecase.NewUserManager(userRepository, tokenService, bcryptHasher, tokenTTLs)
	userHandler := handler.NewUserHandler(userManager)
	userRegistrar := router.NewUserRegistrar(userHandler)
	registrars := provideRegistrars(userRegistrar)
	server := delivery.NewServer(cfg, registrars, tokenService)
	return server, nil
}
